apiVersion: instana.io/v1beta2
kind: Unit
metadata:
  name: tenant0-unit0
  namespace: instana-units
spec:
  # Must refer to the name of the Core object we created above
  coreName: instana-core

  # Must refer to the namespace that the associated Core object we created above
  coreNamespace: instana-core

  # The name of the tenant
  tenantName: tenant0

  # The name of the unit within the tenant
  unitName: unit0

  # The same rules apply as for Cores. May be ommitted. Default is 'medium'
  resourceProfile: small
