apiVersion: beeinstana.instana.com/v1beta1
kind: BeeInstana
metadata:
  name: instana-beeinstana
  namespace: "instana-beeinstana"
spec:
  version: 1.1.3
  kafkaSettings:
    brokers:
      - instana-kafka-kafka-bootstrap.instana-kafka.svc:9092
  config:
    cpu: 200m
    memory: 200Mi
    replicas: 1
  ingestor:
    cpu: 1
    memory: 1Gi
    limitMemory: true
    env: on-prem
    metricsTopic: raw_metrics
    replicas: 1
  aggregator:
    cpu: 1
    memory: 1Gi
    limitMemory: true
    mirrors: 1
    shards: 1
    volumes:
      live:
        size: "${DATASTORE_SIZE_BEEINSTANA}"
        storageClass: "${DATASTORE_STORAGE_CLASS_BEEINSTANA}"
