# The initial password for the admin user
adminPassword:
# Diffie-Hellman parameters to use
dhParams:
# The download key you received from us
downloadKey:
# The sales key you received from us
salesKey:
# Seed for creating crypto tokens. Pick a random 12 char string
tokenSecret: mytokensecret
# Configuration for raw spans storage
#rawSpansStorageConfig:
  # Required if using S3 or compatible and credentials should be configured.
  # Not required if using IRSA on EKS.
  #s3Config:
    #accessKeyId: ...
    #secretAcessKey: ...
  # Required if using Google Cloud Storage and credentials should be configured.
  # Not required if using GKE with workload identity.
  #gcloudConfig:
    #serviceAccountKey: ...
# SAML/OIDC configuration
serviceProviderConfig:
  # Password for the key/cert file
  keyPassword: "${INSTANA_KEY_PASSPHRASE}"
  # The combined key/cert file
  pem:
# Required if a proxy is configured that needs authentication
#proxyConfig:
  # Proxy user
  #user: myproxyuser
  # Proxy password
  #password: my proxypassword
#emailConfig:
  # Required if SMTP is used for sending e-mails and authentication is required
  #smtpConfig:
  #  user: mysmtpuser
  #  password: mysmtppassword
  # Required if using for sending e-mail and credentials should be configured.
  # Not required if using IRSA on EKS.
  #sesConfig:
  #  accessKeyId: ...
  #  secretAcessKey: ...

# NOTE: the passwords will be dynamically replaced with actual value
# Refer to scripts/12-init-instana.sh function "installing-instana-server-secret-instana-core"
datastoreConfigs: 
  cassandraConfigs:
    - user: instana
      # kubectl get secret instana-cassandra -n instana-cassandra --template='{{index .data.password | base64decode}}'
      password: "--WILL BE UPDATED BY SCRIPTS--"
      adminUser: instanaadmin
      # kubectl get secret instana-cassandra-admin -n instana-cassandra --template='{{index .data.password | base64decode}}'
      adminPassword: "--WILL BE UPDATED BY SCRIPTS--"
  clickhouseConfigs:
    - user: instana
      password: "--WILL BE UPDATED BY SCRIPTS--"
      adminUser: instanaadmin
      adminPassword: "--WILL BE UPDATED BY SCRIPTS--"
  elasticsearchConfig:
    user: instana
    # kubectl get secret instana-elasticsearch -n instana-elasticsearch --template='{{index .data.password | base64decode}}'
    password: "--WILL BE UPDATED BY SCRIPTS--"
    adminUser: instanaadmin
    adminPassword: "--WILL BE UPDATED BY SCRIPTS--"
  kafkaConfig:
    adminUser: instanaadmin
    # kubectl get secret instanaadmin -n instana-kafka --template='{{index .data.password | base64decode}}'
    adminPassword: "--WILL BE UPDATED BY SCRIPTS--"
    consumerUser: instana
    # kubectl get secret instana -n instana-kafka --template='{{index .data.password | base64decode}}'
    consumerPassword: "--WILL BE UPDATED BY SCRIPTS--"
    producerUser: instana
    # kubectl get secret instana -n instana-kafka --template='{{index .data.password | base64decode}}'
    producerPassword: "--WILL BE UPDATED BY SCRIPTS--"
  postgresConfigs:
    - user: postgres
      # kubectl get secret postgres.instana-postgres.credentials.postgresql.acid.zalan.do -n instana-postgres --template='{{index .data.password | base64decode}}'
      password: "--WILL BE UPDATED BY SCRIPTS--" 
      adminUser: postgres
      adminPassword: "--WILL BE UPDATED BY SCRIPTS--"
  beeInstanaConfig:
    user: instana
    # kubectl get secret instana-beeinstana-admin -n instana-beeinstana --template='{{index .data.password | base64decode}}'
    password: "--WILL BE UPDATED BY SCRIPTS--"
    # adminUser: bee
    # adminPassword: "--WILL BE UPDATED BY SCRIPTS--"
