apiVersion: instana.io/v1beta2
kind: Core
metadata:
  name: instana-core
  namespace: instana-core
spec:
  agentAcceptorConfig:
    # Host for the agent acceptor. eg: agent.instana.<xxxx.nip.io>
    host: "agent.${INSTANA_EXPOSED_FQDN}"
    port: ${INSTANA_EXPOSED_PORT_ACCEPTOR}

  # Base domain for Instana. eg: instana.<xxxx.nip.io>
  baseDomain: "${INSTANA_EXPOSED_FQDN}"

  # ComponentConfig to override components' defaults, especially resources
  componentConfigs:
    - name: acceptor
      replicas: 1
      resources:
        requests:
          memory: 1500Mi # defaults 2666Mi
    - name: gateway
      properties:
        - name: nginx.http.server_names_hash_bucket_size
          value: "256" # This is important when FQDN is long, default 128
      resources:
        requests:
          memory: 1500Mi # defaults 2666Mi
    - name: appdata-health-aggregator
      resources:
        requests:
          memory: 1500Mi # defaults 2666Mi
    - name: appdata-health-processor
      resources:
        requests:
          memory: 1500Mi # defaults 2666Mi
    - name: appdata-reader
      resources:
        requests:
          memory: 1500Mi # defaults 2666Mi
    - name: appdata-writer
      resources:
        requests:
          memory: 1500Mi # defaults 2666Mi
    - name: eum-acceptor
      resources:
        requests:
          memory: 1200Mi # defaults 2666Mi
    - name: eum-health-processor
      resources:
        requests:
          memory: 1000Mi # defaults 2666Mi
    - name: eum-processor
      resources:
        requests:
          memory: 1500Mi # defaults 2666Mi
    - name: gateway
      resources:
        requests:
          memory: 1200Mi # defaults 2666Mi
    - name: js-stack-trace-translator
      resources:
        requests:
          memory: 1200Mi # defaults 2666Mi
    - name: sli-evaluator
      resources:
        requests:
          memory: 1200Mi # defaults 2666Mi
  # DatastoreConfigs
  datastoreConfigs:
    cassandraConfigs:
      - hosts: [ instana-instana-cassandra-service.instana-cassandra ]
        datacenter: instana-cassandra
        authEnabled: true
        replicationFactor: 1
    clickhouseConfigs:
      - hosts: [ chi-instana-clickhouse-local-0-0.instana-clickhouse ]
        clusterName: local
        authEnabled: true
    elasticsearchConfig:
      hosts: [ instana-elasticsearch-es-http.instana-elasticsearch ]
      clusterName: onprem_onprem
      authEnabled: true
    kafkaConfig:
      hosts: [ instana-kafka-kafka-bootstrap.instana-kafka ]
      authEnabled: true
      saslMechanism: SCRAM-SHA-512
    postgresConfigs:
      - hosts: [ instana-postgres.instana-postgres ]
        authEnabled: true
    beeInstanaConfig:
      hosts: [ aggregators.instana-beeinstana ]
      clustered: true
      authEnabled: true
  # Storage configs
  storageConfigs:
    rawSpans:
      pvcConfig:
        storageClassName: ${DATASTORE_STORAGE_CLASS_SPANS}
        resources:
          requests:
            storage: ${DATASTORE_SIZE_SPANS}
        accessModes:
          - ReadWriteOnce # local-path-config can support ReadWriteOnce only
    synthetics:
      pvcConfig:
        storageClassName: ${DATASTORE_STORAGE_CLASS_SYNTHETICS}
        resources:
          requests:
            storage: ${DATASTORE_SIZE_SYNTHETICS}
        accessModes:
          - ReadWriteOnce
    syntheticsKeystore:
      pvcConfig:
        storageClassName: ${DATASTORE_STORAGE_CLASS_SYNTHETICS}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: ${DATASTORE_SIZE_SYNTHETICS}
  # Feature Flags
  featureFlags:
    # BeeInstana
    - name: feature.beeinstana.infra.metrics.enabled
      enabled: true
    - name: feature.infra.explore.presentation.enabled
      enabled: true
    # Logging
    # - name: feature.logging.enabled
    #   enabled: true
    # Managing actions: https://www.ibm.com/docs/en/instana-observability/current?topic=instana-managing-actions-open-beta
    # - name: feature.automation.enabled
    #   enabled: true
    # - name: feature.action.automation.enabled
    #   enabled: true
    # Synthetic monitoring: https://www.ibm.com/docs/en/instana-observability/current?topic=instana-synthetic-monitoring
    # - name: feature.synthetics.enabled
    #   enabled: true
    # - name: feature.synthetic.smart.alerts.enabled
    #   enabled: true
    # - name: feature.synthetic.create.test.advance.mode.enabled
    #   enabled: true
    # - name: feature.synthetic.browser.create.test.enabled
    #   enabled: true
    # - name: feature.synthetic.browser.script.enabled
    #   enabled: true
  # SMTP
  emailConfig:
    smtpConfig:
      from: test@example.com
      host: example.com
      port: 465
      useSSL: false
  imageConfig:
    registry: artifact-public.instana.io
  resourceProfile: small
  imagePullSecrets:
    - name: instana-registry
