# The initial password for the admin user
adminPassword:
# Diffie-Hellman parameters to use
dhParams:
# The download key you received from us
downloadKey:
# The sales key you received from us
salesKey:
# Seed for creating crypto tokens. Pick a random 12 char string
tokenSecret: mytokensecret
# Configuration for raw spans storage
#rawSpansStorageConfig:
  # Required if using S3 or compatible and credentials should be configured.
  # Not required if using IRSA on EKS.
  #s3Config:
    #accessKeyId: ...
    #secretAcessKey: ...
  # Required if using Google Cloud Storage and credentials should be configured.
  # Not required if using GKE with workload identity.
  #gcloudConfig:
    #serviceAccountKey: ...
# SAML/OIDC configuration
serviceProviderConfig:
  # Password for the key/cert file
  keyPassword: "${INSTANA_KEY_PASSPHRASE}"
  # The combined key/cert file
  pem:
# Required if a proxy is configured that needs authentication
#proxyConfig:
  # Proxy user
  #user: myproxyuser
  # Proxy password
  #password: my proxypassword
#emailConfig:
  # Required if SMTP is used for sending e-mails and authentication is required
  #smtpConfig:
  #  user: mysmtpuser
  #  password: mysmtppassword
  # Required if using for sending e-mail and credentials should be configured.
  # Not required if using IRSA on EKS.
  #sesConfig:
  #  accessKeyId: ...
  #  secretAcessKey: ...
datastoreConfigs: 
  cassandraConfigs:
    - keyspaces:
        - profiles
        - spans
        - metrics
        - state
      user: cassandra
      password: cassandra
      adminUser: cassandra
      adminPassword: cassandra
  clickhouseConfigs:
    - schemas:
        - application
      user: clickhouse_user
      password: clickhouse_pass
      adminUser: clickhouse_user
      adminPassword: clickhouse_pass
  elasticsearchConfig:
    user: elasticsearch_user
    password: elasticsearch_pass
    adminUser: elasticsearch_user
    adminPassword: elasticsearch_pass
  kafkaConfig:
    adminUser: kafka_user
    adminPassword: kafka_pass
    consumerUser: kafka_user
    consumerPassword: kafka_pass
    producerUser: kafka_user
    producerPassword: kafka_pass
  postgresConfigs:
    - databases:
        - butlerdb
        - tenantdb
        - sales
      user: postgres_user
      password: postgres_pass
      adminUser: postgres_user
      adminPassword: postgres_pass
  beeInstanaConfig:
    user: bee_user
    password: bee_pass
