apiVersion: v1
kind: Secret
type: Generic
metadata:
  name: instana-datastores
  namespace: instana-datastores
stringData:
  config.yaml: |
    cassandra:
      - name: default
        adminUser: cassandra
        adminPassword: cassandra
    clickhouse:
      - name: default
        adminUser: clickhouse_user
        adminPassword: clickhouse_pass
    elasticsearch:
      name: default
      adminUser: elasticsearch_user
      adminPassword: elasticsearch_pass
    kafka:
      name: default
      adminUser: kafka_user
      adminPassword: kafka_pass
    postgres:
      - name: default
        adminUser: postgres_user
        adminPassword: postgres_pass
    beeInstana:
      name: default
      user: bee_user
      password: bee_pass
