kind: Secret
apiVersion: v1
metadata:
  name: instana-cassandra
  namespace: instana-cassandra
  annotations:
    "helm.sh/resource-policy": keep
stringData:
  username: "instana"
  password: "${CASSANDRA_PASSWORD}"
type: kubernetes.io/basic-auth

---
kind: Secret
apiVersion: v1
metadata:
  name: instana-cassandra-admin
  namespace: instana-cassandra
  annotations:
    "helm.sh/resource-policy": keep
stringData:
  username: "instanaadmin"
  password: "${CASSANDRA_ADMIN_PASSWORD}"
type: kubernetes.io/basic-auth

---
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: instana-cassandra
  namespace: instana-cassandra
spec:
  clusterName: instana
  serverType: cassandra
  serverImage: artifact-public.instana.io/self-hosted-images/3rd-party/k8ssandra-management-api-for-apache-cassandra:4.1.2_v0.4.0
  systemLoggerImage: artifact-public.instana.io/self-hosted-images/3rd-party/system-logger:1.18.2_v0.2.0
  k8ssandraClientImage: artifact-public.instana.io/self-hosted-images/3rd-party/k8ssandra-k8ssandra-client:0.2.2_v0.2.0
  serverVersion: "4.1.2"
  imagePullPolicy: Always
  podTemplateSpec:
    spec:
      imagePullSecrets:
      - name: instana-registry
      containers:
      - name: cassandra
  managementApiAuth:
    insecure: {}
  size: 1
  allowMultipleNodesPerWorker: false
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 4
      memory: 8Gi
  storageConfig:
    cassandraDataVolumeClaimSpec:
      accessModes:
        - ReadWriteOnce
      storageClassName: "${DATASTORE_STORAGE_CLASS_CASSANDRA}"
      resources:
        requests:
          storage: "${DATASTORE_SIZE_CASSANDRA}"
  superuserSecretName: instana-cassandra-admin
  users:
    - secretName: instana-cassandra
      superuser: true
  config:
    jvm-server-options:
      initial_heap_size: "2G"
      max_heap_size: "8G"
      additional-jvm-opts:
        - -Dcassandra.allow_unsafe_aggressive_sstable_expiration=true
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
      memtable_flush_writers: 8
      auto_snapshot: false
      gc_warn_threshold_in_ms: 10000
      otc_coalescing_strategy: DISABLED
      memtable_allocation_type: offheap_objects
      num_tokens: 256
      drop_compact_storage_enabled: true
