apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: instana-clickhouse
  namespace: instana-clickhouse
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: instana-clickhouse-data-volume
      logVolumeClaimTemplate: instana-clickhouse-log-volume
      serviceTemplate: service-template
  configuration:
    files:
      config.d/storage.xml: |
        <yandex>
          <storage_configuration>
            <disks>
              <default/>
            </disks>
            <policies>
              <logs_policy>
                <volumes>
                  <data>
                    <disk>default</disk>
                  </data>
                </volumes>
              </logs_policy>
            </policies>
          </storage_configuration>
        </yandex>
    clusters:
      - name: local
        templates:
          podTemplate: clickhouse
        layout:
          shardsCount: 1
          replicasCount: 1
    zookeeper:
      nodes:
        - host: instana-zookeeper-headless.instana-clickhouse
    profiles:
      default/max_memory_usage: 8000000000  # 8GB
      default/joined_subquery_requires_alias: 0
      default/max_execution_time: 100
      default/max_query_size: 1048576
      default/use_uncompressed_cache: 0
      default/enable_http_compression: 1
      default/load_balancing: random
      default/background_pool_size: 32
      default/background_schedule_pool_size: 32
      default/distributed_directory_monitor_split_batch_on_failure: 1
      default/distributed_directory_monitor_batch_inserts: 1
      default/insert_distributed_sync: 1
      default/log_queries: 1
      default/log_query_views: 1
      default/max_threads: 16
    quotas:
      default/interval/duration: 3600
      default/interval/queries: 0
      default/interval/errors: 0
      default/interval/result_rows: 0
      default/interval/read_rows: 0
      default/interval/execution_time: 0
    users:
      default/password: "${CLICKHOUSE_PASSWORD}"
      default/networks/ip: "::/0"
      instana/password: "${CLICKHOUSE_PASSWORD}"
      instana/networks/ip: "::/0"
      instanaadmin/password: "${CLICKHOUSE_ADMIN_PASSWORD}"
      instanaadmin/networks/ip: "::/0"
  templates:
    podTemplates:
      - name: clickhouse
        spec:
          containers:
            - name: instana-clickhouse
              image: artifact-public.instana.io/self-hosted-images/k8s/clickhouse:23.3.10.5-1-lts-ibm_v0.29.0
              imagePullPolicy: IfNotPresent
              command:
                - clickhouse-server
                - --config-file=/etc/clickhouse-server/config.xml
              resources:
                requests:
                  cpu: 1000m
                  memory: 2Gi
            - name: clickhouse-log
              image: registry.access.redhat.com/ubi9/ubi-minimal:9.3-1475
              command:
              - /bin/sh
              - -c
              - --
              args:
                - while true; do sleep 30; done;
              imagePullPolicy: IfNotPresent
          imagePullSecrets:
            - name: instana-registry
          securityContext:
            fsGroup: 0
            runAsGroup: 0
            runAsUser: 1001
    volumeClaimTemplates:
      - name: instana-clickhouse-data-volume
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: "${DATASTORE_STORAGE_CLASS_CLICKHOUSE}"
          resources:
            requests:
              storage: "${DATASTORE_SIZE_CLICKHOUSE_DATA}"
      - name: instana-clickhouse-log-volume
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: "${DATASTORE_STORAGE_CLASS_CLICKHOUSE}"
          resources:
            requests:
              storage: "${DATASTORE_SIZE_CLICKHOUSE_LOG}"
    serviceTemplates:
      - name: service-template
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: ClusterIP
