apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: instana-kafka
  namespace: instana-kafka
  labels:
    strimzi.io/cluster: instana-kafka
spec:
  kafka:
    version: 3.6.0
    replicas: 1
    listeners:
      - name: scram
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
        configuration:
          useServiceDnsDomain: true
    authorization:
      type: simple
      superUsers:
        - CN=instanaadmin
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          class: "${DATASTORE_STORAGE_CLASS_KAFKA}"
          size: "${DATASTORE_SIZE_KAFKA}"
          deleteClaim: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      class: "${DATASTORE_STORAGE_CLASS_KAFKA_ZK}"
      size: "${DATASTORE_SIZE_KAFKA_ZK}"
      deleteClaim: true
  entityOperator:
    template:
      pod:
        tmpDirSizeLimit: 100Mi
    topicOperator: {}
    userOperator: {}

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: instana
  namespace: instana-kafka
  labels:
    strimzi.io/cluster: instana-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operations:
          - Alter
          - Read
          - Write
          - Create
          - Delete
          - Describe
        host: "*"
      - resource:
          type: group
          name: "*"
          patternType: literal
        operations:
          - Alter
          - Read
          - Write
          - Create
          - Delete
          - Describe
        host: "*"

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: instanaadmin
  namespace: instana-kafka
  labels:
    strimzi.io/cluster: instana-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operations:
          - All
        host: "*"
      - resource:
          type: group
          name: "*"
          patternType: literal
        operations:
          - All
        host: "*"
