apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: instana-postgres
  namespace: instana-postgres
spec:
  patroni:
    pg_hba:
      - local     all          all                            trust
      - host      all          all          0.0.0.0/0         md5
      - local     replication  standby                        trust
      - hostssl   replication  standby      all               md5
      - hostnossl all          all          all               reject
      - hostssl   all          all          all               md5
  dockerImage: ghcr.io/zalando/spilo-15:3.0-p1
  teamId: instana
  numberOfInstances: 1
  spiloRunAsUser: 101
  spiloFSGroup: 101
  spiloRunAsGroup: 101
  postgresql:
    version: "15"
    parameters:  # Expert section
      shared_buffers: "32MB"
  volume:
    size: "${DATASTORE_SIZE_POSTGRES}"
    storageClass: "${DATASTORE_STORAGE_CLASS_POSTGRES}"
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 4Gi
